#!/usr/bin/env python3

"""Create the label-blind six-ligand CGenFF request package for v1.5 MD."""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from openbabel import pybel


ROOT = Path(__file__).resolve().parent
DOCKING_MANIFEST = ROOT / "outputs" / "v1.4" / "docking" / "literature_pilot_2025_ligand_manifest.json"
DEFAULT_OUTPUT = ROOT / "outputs" / "v1.5" / "md" / "cgenff_requests"
CGENFF_VERSION = "4.6"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_one_sdf(path: Path):
    molecules = list(pybel.readfile("sdf", str(path)))
    if len(molecules) != 1:
        raise RuntimeError(f"Expected one molecule in {path}, found {len(molecules)}")
    return molecules[0]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    docking = json.loads(DOCKING_MANIFEST.read_text(encoding="utf-8"))
    candidate_sources = {entry["candidate_id"]: ROOT / entry["path"] for entry in docking["entries"]}
    requests = [
        ("NEC", "NECA active-control ligand", ROOT / "data" / "raw" / "5G53_NEC_ideal.sdf", 0),
        ("ZMA", "ZM241385 inactive-control ligand", ROOT / "data" / "raw" / "5NM4_ZMA_A507.sdf", 0),
        ("C5A", "LIT25-RL-C5", candidate_sources["LIT25-RL-C5"], -1),
        ("C7A", "LIT25-RL-C7", candidate_sources["LIT25-RL-C7"], 0),
        ("C9A", "LIT25-RL-C9", candidate_sources["LIT25-RL-C9"], 0),
        ("PGD2", "LIT25-MET-PGD2", candidate_sources["LIT25-MET-PGD2"], -1),
    ]
    args.output.mkdir(parents=True, exist_ok=True)
    entries = []
    for residue_name, molecule_id, source, expected_charge in requests:
        if not source.exists():
            raise FileNotFoundError(source)
        molecule = read_one_sdf(source)
        observed_charge = int(molecule.charge)
        if observed_charge != expected_charge:
            raise RuntimeError(
                f"Unexpected formal charge for {molecule_id}: expected {expected_charge}, observed {observed_charge}"
            )
        molecule.title = residue_name
        output = args.output / f"{residue_name}.mol2"
        molecule.write("mol2", str(output), overwrite=True)
        roundtrip = list(pybel.readfile("mol2", str(output)))
        if len(roundtrip) != 1 or len(roundtrip[0].atoms) != len(molecule.atoms):
            raise RuntimeError(f"MOL2 round-trip failed for {molecule_id}")
        entries.append({
            "residue_name": residue_name,
            "molecule_id": molecule_id,
            "functional_label_blinded": molecule_id.startswith("LIT25-"),
            "expected_formal_charge": expected_charge,
            "observed_formal_charge": observed_charge,
            "atom_count": len(molecule.atoms),
            "formula": molecule.formula,
            "source_path": str(source.relative_to(ROOT)),
            "source_sha256": sha256(source),
            "request_mol2_path": str(output.relative_to(ROOT)),
            "request_mol2_sha256": sha256(output),
            "parameter_status": "pending_external_cgenff_generation_and_penalty_audit",
        })

    manifest = {
        "schema_version": 1,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "specification_id": "a2a-md-cgenff-request-v1.5",
        "requested_cgenff_version": CGENFF_VERSION,
        "version_rationale": "CGenFF 4.6 is required for compatibility with the frozen CHARMM July 2024 topology/parameter package.",
        "candidate_labels_loaded": False,
        "molecule_count": len(entries),
        "input_format": "Tripos MOL2 generated by Open Babel 3.2.1 from frozen SDF structures",
        "entries": entries,
        "required_return_files": [
            "CGenFF CHARMM stream/topology and parameter output for each molecule",
            "CGenFF program and force-field version metadata",
            "per-atom charge penalties and bonded-parameter penalties",
            "net-charge verification and any manual parameter refinement record",
        ],
        "audit_rule": "Any charge penalty above 50 or bonded-parameter penalty above 50 blocks production; penalties from 10 through 50 require a documented computational sensitivity audit. Do not combine or rename ligands before the audit.",
        "status": "request_inputs_ready_parameters_pending",
    }
    manifest_path = args.output / "request_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
